# Dataset Understanding and Problem Framing

## Problem Statement

The objective of this project is to perform sentiment analysis on the IMDB movie reviews dataset. Given a movie review as text, the task is to classify it as expressing either positive or negative sentiment. The project further aims to compare multiple text vectorization techniques to analyze their impact on classification performance.

## Dataset Description

The IMDB dataset consists of 50,000 movie reviews labeled as either positive or negative. The dataset is balanced, making accuracy a suitable primary evaluation metric. Reviews vary in length and contain informal language, HTML tags, and punctuation, making it a suitable benchmark for natural language processing tasks.

# Importing Dependencies

In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Embedding, LSTM, Input
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

# Data Loading

## Load Dataset

In [2]:
df=pd.read_csv("IMDB Dataset.csv")

In [3]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [4]:
df.tail()

                                                  review sentiment
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

## Dataset Shape

In [5]:
df.shape

(50000, 2)

## 'Sentiment' category count

In [6]:
df['sentiment'].value_counts()

sentiment
positive    25000
negative    25000
Name: count, dtype: int64

## Encode target variable

In [7]:
df['sentiment'] = df['sentiment'].map({'positive': 1, 'negative': 0}).astype(int)

In [8]:
df.head()

                                              review  sentiment
0  One of the other reviewers has mentioned that ...          1
1  A wonderful little production. <br /><br />The...          1
2  I thought this was a wonderful way to spend ti...          1
3  Basically there's a family where a little boy ...          0
4  Petter Mattei's "Love in the Time of Money" is...          1

In [9]:
df['sentiment'].value_counts()

sentiment
1    25000
0    25000
Name: count, dtype: int64

# Train Test Split

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
train_data,test_data=train_test_split(df,test_size=0.2,random_state=42)

In [12]:
train_data.head()

                                                  review  sentiment
39087  That's what I kept asking myself during the ma...          0
30893  I did not watch the entire movie. I could not ...          0
45278  A touching love story reminiscent of In the M...          1
16398  This latter-day Fulci schlocker is a totally a...          0
13653  First of all, I firmly believe that Norwegian ...          0

In [13]:
test_data.head()

                                                  review  sentiment
33553  I really liked this Summerslam due to the look...          1
9427   Not many television shows appeal to quite as m...          1
199    The film quickly gets to a major chase scene w...          0
12447  Jane Austen would definitely approve of this o...          1
39489  Expectations were somewhat high for me when I ...          0

In [14]:
print(train_data.shape)
print(test_data.shape)

(40000, 2)
(10000, 2)

# Data Preprocessing

## Tokenize Data

In [15]:
tokenizer = Tokenizer(num_words=5000)
tokenizer.fit_on_texts(train_data['review'])
X_train = pad_sequences(tokenizer.texts_to_sequences(train_data['review']), maxlen=200)
X_test  = pad_sequences(tokenizer.texts_to_sequences(test_data['review']),  maxlen=200)

In [16]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'a': 3,
 'of': 4,
 'to': 5,
 'is': 6,
 'br': 7,
 'in': 8,
 'it': 9,
 'i': 10,
 'this': 11,
 'that': 12,
 'was': 13,
 'as': 14,
 'for': 15,
 'with': 16,
 'movie': 17,
 'but': 18,
 'film': 19,
 'on': 20,
 'not': 21,
 'you': 22,
 'are': 23,
 'his': 24,
 'have': 25,
 'be': 26,
 'one': 27,
 'he': 28,
 'all': 29,
 'at': 30,
 'by': 31,
 'an': 32,
 'they': 33,
 'so': 34,
 'from': 35,
 'who': 36,
 'like': 37,
 'or': 38,
 'just': 39,
 'her': 40,
 'out': 41,
 'about': 42,
 'if': 43,
 "it's": 44,
 'has': 45,
 'there': 46,
 'some': 47,
 'what': 48,
 'good': 49,
 'more': 50,
 'very': 51,
 'when': 52,
 'up': 53,
 'no': 54,
 'time': 55,
 'my': 56,
 'even': 57,
 'she': 58,
 'would': 59,
 'which': 60,
 'only': 61,
 'story': 62,
 'really': 63,
 'see': 64,
 'their': 65,
 'had': 66,
 'can': 67,
 'me': 68,
 'well': 69,
 'were': 70,
 'we': 71,
 'than': 72,
 'much': 73,
 'bad': 74,
 'been': 75,
 'do': 76,
 'get': 77,
 'great': 78,
 'also': 79,
 'will': 80,
 'other': 81,
 'into': 82,
 'people': 83,
 'because': 84,
 'first': 85,
 'how': 86,
 'him': 87,
 'most': 88,
 "don't": 89,
 'made': 90,
 'then': 91,
 'them': 92,
 'make': 93,
 'its': 94,
 'way': 95,
 'movies': 96,
 'could': 97,
 'too': 98,
 'any': 99,
 'after': 100,
 'think': 101,
 'characters': 102,
 'watch': 103,
 'films': 104,
 'seen': 105,
 'two': 106,
 'many': 107,
 'character': 108,
 'being': 109,
 'plot': 110,
 'never': 111,
 'acting': 112,
 'love': 113,
 'life': 114,
 'best': 115,
 'did': 116,
 'where': 117,
 'know': 118,
 'little': 119,
 'show': 120,
 'over': 121,
 'ever': 122,
 'off': 123,
 'does': 124,
 'your': 125,
 'better': 126,
 'end': 127,
 'scene': 128,
 'man': 129,
 'still': 130,
 'say': 131,
 'these': 132,
 'here': 133,
 'scenes': 134,
 'why': 135,
 'while': 136,
 'something': 137,
 'such': 138,
 'go': 139,
 'through': 140,
 'back': 141,
 'should': 142,
 'real': 143,
 "i'm": 144,
 'those': 145,
 'watching': 146,
 'now': 147,
 'thing': 148,
 "doesn't": 149,
 'though': 150,
 'actors': 151,
 'years': 152,
 "didn't": 153,
 'funny': 154,
 '10': 155,
 'old': 156,
 'another': 157,
 'actually': 158,
 'before': 159,
 'work': 160,
 'makes': 161,
 'nothing': 162,
 'look': 163,
 'going': 164,
 'find': 165,
 'director': 166,
 'same': 167,
 'lot': 168,
 'new': 169,
 'again': 170,
 'few': 171,
 'every': 172,
 'part': 173,
 'cast': 174,
 'us': 175,
 'things': 176,
 'down': 177,
 'quite': 178,
 'world': 179,
 'want': 180,
 'pretty': 181,
 'horror': 182,
 'around': 183,
 'seems': 184,
 'take': 185,
 'got': 186,
 'thought': 187,
 'however': 188,
 'young': 189,
 'long': 190,
 'fact': 191,
 'enough': 192,
 'big': 193,
 "can't": 194,
 'both': 195,
 'give': 196,
 "that's": 197,
 "i've": 198,
 'may': 199,
 'own': 200,
 'series': 201,
 'action': 202,
 'right': 203,
 'without': 204,
 'must': 205,
 'between': 206,
 'music': 207,
 'comedy': 208,
 'original': 209,
 'times': 210,
 'always': 211,
 'saw': 212,
 'come': 213,
 'almost': 214,
 "isn't": 215,
 'role': 216,
 'gets': 217,
 'point': 218,
 'least': 219,
 'whole': 220,
 'done': 221,
 'interesting': 222,
 "there's": 223,
 'guy': 224,
 'far': 225,
 'script': 226,
 'minutes': 227,
 'bit': 228,
 'feel': 229,
 '2': 230,
 'making': 231,
 'anything': 232,
 'since': 233,
 'family': 234,
 'am': 235,
 'might': 236,
 'probably': 237,
 'last': 238,
 'tv': 239,
 "he's": 240,
 'performance': 241,
 'away': 242,
 'kind': 243,
 'worst': 244,
 'yet': 245,
 'fun': 246,
 'hard': 247,
 'sure': 248,
 'anyone': 249,
 'girl': 250,
 'rather': 251,
 'found': 252,
 'each': 253,
 'played': 254,
 'day': 255,
 'although': 256,
 'looking': 257,
 'woman': 258,
 'our': 259,
 'believe': 260,
 'screen': 261,
 'having': 262,
 'especially': 263,
 'trying': 264,
 'course': 265,
 'dvd': 266,
 'everything': 267,
 'set': 268,
 'ending': 269,
 'put': 270,
 'goes': 271,
 'maybe': 272,
 'comes': 273,
 'shows': 274,
 'place': 275,
 'worth': 276,
 'book': 277,
 'different': 278,
 'main': 279,
 'three': 280,
 'effects': 281,
 'once': 282,
 'sense': 283,
 'watched': 284,
 'looks': 285,
 'reason': 286,
 'money': 287,
 'actor': 288,
 'american': 289,
 'true': 290,
 "wasn't": 291,
 'together': 292,
 'play': 293,
 'job': 294,
 'someone': 295,
 'war': 296,
 'high': 297,
 'special': 298,
 'instead': 299,
 'year': 300,
 'everyone': 301,
 'during': 302,
 '1': 303,
 'later': 304,
 'half': 305,
 'takes': 306,
 'said': 307,
 'plays': 308,
 'left': 309,
 'audience': 310,
 'himself': 311,
 'seem': 312,
 'night': 313,
 'seeing': 314,
 'beautiful': 315,
 'excellent': 316,
 'shot': 317,
 'john': 318,
 'house': 319,
 'black': 320,
 'version': 321,
 'idea': 322,
 'fan': 323,
 'mind': 324,
 'death': 325,
 'wife': 326,
 'star': 327,
 'budget': 328,
 'short': 329,
 'used': 330,
 'nice': 331,
 'second': 332,
 'poor': 333,
 'simply': 334,
 '3': 335,
 'else': 336,
 'completely': 337,
 "you're": 338,
 'read': 339,
 'top': 340,
 'along': 341,
 'either': 342,
 'home': 343,
 'boring': 344,
 'less': 345,
 'men': 346,
 'help': 347,
 'dead': 348,
 'line': 349,
 'friends': 350,
 'try': 351,
 'production': 352,
 'father': 353,
 'enjoy': 354,
 'kids': 355,
 'given': 356,
 'camera': 357,
 'until': 358,
 'need': 359,
 'wrong': 360,
 'low': 361,
 'use': 362,
 'classic': 363,
 'full': 364,
 'performances': 365,
 'rest': 366,
 'next': 367,
 'stupid': 368,
 'truly': 369,
 'school': 370,
 'couple': 371,
 'hollywood': 372,
 'video': 373,
 'recommend': 374,
 'tell': 375,
 'awful': 376,
 'start': 377,
 'sex': 378,
 'let': 379,
 'mean': 380,
 'terrible': 381,
 'women': 382,
 'came': 383,
 'name': 384,
 'perhaps': 385,
 'understand': 386,
 'moments': 387,
 'wonderful': 388,
 'remember': 389,
 'getting': 390,
 'episode': 391,
 'itself': 392,
 'human': 393,
 'keep': 394,
 'face': 395,
 'style': 396,
 'small': 397,
 'early': 398,
 'stars': 399,
 'written': 400,
 'person': 401,
 'head': 402,
 'definitely': 403,
 'playing': 404,
 'others': 405,
 'perfect': 406,
 'doing': 407,
 'often': 408,
 'gives': 409,
 'dialogue': 410,
 'lines': 411,
 'mother': 412,
 'case': 413,
 'finally': 414,
 "couldn't": 415,
 'piece': 416,
 'title': 417,
 'boy': 418,
 'went': 419,
 'certainly': 420,
 'live': 421,
 'oh': 422,
 'liked': 423,
 'absolutely': 424,
 'laugh': 425,
 'sort': 426,
 'loved': 427,
 'hope': 428,
 'worse': 429,
 'entertaining': 430,
 'yes': 431,
 'lost': 432,
 'become': 433,
 'several': 434,
 '5': 435,
 'based': 436,
 'sound': 437,
 'entire': 438,
 'friend': 439,
 'called': 440,
 'supposed': 441,
 'overall': 442,
 'picture': 443,
 'felt': 444,
 'problem': 445,
 'mr': 446,
 'cinema': 447,
 'guys': 448,
 'waste': 449,
 '4': 450,
 'totally': 451,
 'drama': 452,
 'beginning': 453,
 'care': 454,
 'direction': 455,
 'against': 456,
 'white': 457,
 'dark': 458,
 'under': 459,
 'wanted': 460,
 'seemed': 461,
 'game': 462,
 'humor': 463,
 'fans': 464,
 'turn': 465,
 "you'll": 466,
 'lives': 467,
 'children': 468,
 "she's": 469,
 'lead': 470,
 'already': 471,
 'despite': 472,
 'evil': 473,
 'example': 474,
 'throughout': 475,
 'final': 476,
 'becomes': 477,
 'quality': 478,
 'guess': 479,
 'unfortunately': 480,
 'days': 481,
 'able': 482,
 'history': 483,
 'fine': 484,
 "i'd": 485,
 'writing': 486,
 'heart': 487,
 'side': 488,
 'wants': 489,
 'flick': 490,
 'horrible': 491,
 'b': 492,
 'killer': 493,
 'son': 494,
 'matter': 495,
 'run': 496,
 'kill': 497,
 '\x96': 498,
 'amazing': 499,
 'michael': 500,
 'enjoyed': 501,
 'close': 502,
 'art': 503,
 'etc': 504,
 'works': 505,
 'act': 506,
 'behind': 507,
 'tries': 508,
 'past': 509,
 'gave': 510,
 'brilliant': 511,
 "they're": 512,
 'eyes': 513,
 "won't": 514,
 'directed': 515,
 'genre': 516,
 'expect': 517,
 'turns': 518,
 'town': 519,
 'themselves': 520,
 'hand': 521,
 'favorite': 522,
 'car': 523,
 'parts': 524,
 'late': 525,
 'killed': 526,
 'hour': 527,
 'soon': 528,
 'stuff': 529,
 'girls': 530,
 'viewer': 531,
 'actress': 532,
 'obviously': 533,
 'myself': 534,
 'decent': 535,
 'says': 536,
 'highly': 537,
 'thinking': 538,
 'city': 539,
 'group': 540,
 'child': 541,
 'starts': 542,
 'stop': 543,
 'sometimes': 544,
 'heard': 545,
 'anyway': 546,
 'kid': 547,
 'type': 548,
 'self': 549,
 'god': 550,
 'known': 551,
 'happens': 552,
 'except': 553,
 'took': 554,
 'voice': 555,
 'blood': 556,
 'fight': 557,
 'daughter': 558,
 'told': 559,
 'feeling': 560,
 'slow': 561,
 'experience': 562,
 'leave': 563,
 'coming': 564,
 'score': 565,
 'strong': 566,
 'writer': 567,
 'including': 568,
 'stories': 569,
 'violence': 570,
 'happen': 571,
 'extremely': 572,
 'ok': 573,
 'involved': 574,
 'lack': 575,
 'cannot': 576,
 'police': 577,
 'moment': 578,
 'wonder': 579,
 's': 580,
 'age': 581,
 'obvious': 582,
 'crap': 583,
 'living': 584,
 'save': 585,
 'particularly': 586,
 'looked': 587,
 "wouldn't": 588,
 'chance': 589,
 'please': 590,
 'shown': 591,
 'cut': 592,
 'complete': 593,
 'song': 594,
 'attempt': 595,
 'ago': 596,
 'hell': 597,
 'murder': 598,
 'cool': 599,
 'happened': 600,
 'roles': 601,
 'simple': 602,
 'gore': 603,
 'hit': 604,
 'hilarious': 605,
 'taken': 606,
 'english': 607,
 'released': 608,
 'serious': 609,
 'interest': 610,
 'james': 611,
 'opening': 612,
 'hours': 613,
 'robert': 614,
 'brother': 615,
 'david': 616,
 'possible': 617,
 'jokes': 618,
 'number': 619,
 'seriously': 620,
 'across': 621,
 'usually': 622,
 'talent': 623,
 'none': 624,
 'cinematography': 625,
 'yourself': 626,
 'today': 627,
 'order': 628,
 'view': 629,
 'hero': 630,
 'saying': 631,
 'career': 632,
 'alone': 633,
 'reality': 634,
 'sad': 635,
 'exactly': 636,
 'huge': 637,
 'documentary': 638,
 'light': 639,
 'running': 640,
 'annoying': 641,
 'relationship': 642,
 'started': 643,
 'whose': 644,
 'wish': 645,
 'ridiculous': 646,
 'scary': 647,
 'taking': 648,
 'shots': 649,
 'husband': 650,
 'middle': 651,
 'female': 652,
 'important': 653,
 "film's": 654,
 'body': 655,
 'ends': 656,
 'turned': 657,
 'word': 658,
 'four': 659,
 'power': 660,
 'rating': 661,
 'change': 662,
 "i'll": 663,
 'major': 664,
 'opinion': 665,
 'beyond': 666,
 'call': 667,
 'level': 668,
 'somewhat': 669,
 'silly': 670,
 'country': 671,
 'talking': 672,
 'ones': 673,
 'strange': 674,
 'upon': 675,
 'room': 676,
 'usual': 677,
 'knew': 678,
 'words': 679,
 'happy': 680,
 'mostly': 681,
 'disappointed': 682,
 'apparently': 683,
 'episodes': 684,
 'novel': 685,
 'single': 686,
 'basically': 687,
 'attention': 688,
 'modern': 689,
 'problems': 690,
 'jack': 691,
 'knows': 692,
 'miss': 693,
 'finds': 694,
 'non': 695,
 'due': 696,
 'british': 697,
 'musical': 698,
 'thriller': 699,
 'class': 700,
 'cheap': 701,
 'five': 702,
 'television': 703,
 'clearly': 704,
 'talk': 705,
 'events': 706,
 "aren't": 707,
 'add': 708,
 '7': 709,
 'moving': 710,
 'fast': 711,
 'review': 712,
 'local': 713,
 'ten': 714,
 'predictable': 715,
 'sequence': 716,
 'tells': 717,
 'songs': 718,
 '8': 719,
 'team': 720,
 'dialog': 721,
 'straight': 722,
 'space': 723,
 'appears': 724,
 'whether': 725,
 'enjoyable': 726,
 'soundtrack': 727,
 'die': 728,
 'above': 729,
 'entertainment': 730,
 'earth': 731,
 'future': 732,
 'supporting': 733,
 'sets': 734,
 'easily': 735,
 'french': 736,
 'near': 737,
 'hate': 738,
 'giving': 739,
 'lots': 740,
 'within': 741,
 'tried': 742,
 'falls': 743,
 'dull': 744,
 'similar': 745,
 'sequel': 746,
 'suspense': 747,
 'release': 748,
 'filmed': 749,
 'romantic': 750,
 'mention': 751,
 'needs': 752,
 'bring': 753,
 'clear': 754,
 'subject': 755,
 "haven't": 756,
 'comic': 757,
 'working': 758,
 'eye': 759,
 'theme': 760,
 'bunch': 761,
 'george': 762,
 'message': 763,
 'surprised': 764,
 'certain': 765,
 'showing': 766,
 'easy': 767,
 "what's": 768,
 '9': 769,
 'ways': 770,
 't': 771,
 'storyline': 772,
 'stay': 773,
 'sorry': 774,
 'named': 775,
 'effort': 776,
 'sister': 777,
 'among': 778,
 'theater': 779,
 'tale': 780,
 'rock': 781,
 'stand': 782,
 'king': 783,
 'realistic': 784,
 'feature': 785,
 'using': 786,
 'editing': 787,
 'fall': 788,
 'crime': 789,
 'herself': 790,
 'minute': 791,
 'comments': 792,
 'avoid': 793,
 'deal': 794,
 'elements': 795,
 'nearly': 796,
 'typical': 797,
 'buy': 798,
 "'": 799,
 'famous': 800,
 'kept': 801,
 'greatest': 802,
 'feels': 803,
 'doubt': 804,
 'means': 805,
 'check': 806,
 'parents': 807,
 'points': 808,
 'monster': 809,
 'gone': 810,
 'dr': 811,
 'okay': 812,
 'follow': 813,
 'mystery': 814,
 'general': 815,
 'rent': 816,
 'brought': 817,
 're': 818,
 'oscar': 819,
 'actual': 820,
 'viewing': 821,
 'lady': 822,
 'richard': 823,
 'viewers': 824,
 'reviews': 825,
 'fantastic': 826,
 'imagine': 827,
 'learn': 828,
 "you've": 829,
 'material': 830,
 'move': 831,
 'period': 832,
 'form': 833,
 'begins': 834,
 'weak': 835,
 'believable': 836,
 'somehow': 837,
 'red': 838,
 'animation': 839,
 'forget': 840,
 'sequences': 841,
 'peter': 842,
 'leads': 843,
 'figure': 844,
 'fi': 845,
 'deep': 846,
 'sci': 847,
 'hear': 848,
 'particular': 849,
 'open': 850,
 'atmosphere': 851,
 'sit': 852,
 'dog': 853,
 '20': 854,
 'average': 855,
 'killing': 856,
 'surprise': 857,
 'premise': 858,
 'shame': 859,
 'paul': 860,
 'poorly': 861,
 'imdb': 862,
 'whatever': 863,
 'tom': 864,
 'lame': 865,
 'wait': 866,
 'eventually': 867,
 'acted': 868,
 'decided': 869,
 'dance': 870,
 'expected': 871,
 'indeed': 872,
 'box': 873,
 'truth': 874,
 "who's": 875,
 'note': 876,
 'season': 877,
 'doctor': 878,
 'emotional': 879,
 'forced': 880,
 'free': 881,
 'credits': 882,
 'situation': 883,
 'boys': 884,
 'crew': 885,
 'memorable': 886,
 'third': 887,
 'western': 888,
 'hot': 889,
 'romance': 890,
 'sexual': 891,
 'needed': 892,
 'york': 893,
 'difficult': 894,
 'male': 895,
 'gay': 896,
 'cheesy': 897,
 'plus': 898,
 'write': 899,
 'reading': 900,
 'unless': 901,
 'superb': 902,
 'leaves': 903,
 'nature': 904,
 'became': 905,
 'society': 906,
 'air': 907,
 'question': 908,
 'footage': 909,
 'possibly': 910,
 'begin': 911,
 'hands': 912,
 'meets': 913,
 'otherwise': 914,
 'interested': 915,
 'badly': 916,
 'forward': 917,
 'earlier': 918,
 'laughs': 919,
 'quickly': 920,
 'screenplay': 921,
 'setting': 922,
 'incredibly': 923,
 'beauty': 924,
 'effect': 925,
 'background': 926,
 'de': 927,
 'features': 928,
 'e': 929,
 'meet': 930,
 'stage': 931,
 'masterpiece': 932,
 'towards': 933,
 'inside': 934,
 'weird': 935,
 'sounds': 936,
 'comment': 937,
 'nor': 938,
 'japanese': 939,
 'whom': 940,
 'dumb': 941,
 'following': 942,
 'personal': 943,
 'street': 944,
 'copy': 945,
 'result': 946,
 'unique': 947,
 'battle': 948,
 'powerful': 949,
 'water': 950,
 'previous': 951,
 'america': 952,
 'keeps': 953,
 "let's": 954,
 'directing': 955,
 'island': 956,
 'mark': 957,
 'perfectly': 958,
 'development': 959,
 'rate': 960,
 'realize': 961,
 'lee': 962,
 'total': 963,
 'worked': 964,
 'girlfriend': 965,
 'writers': 966,
 'joke': 967,
 'fire': 968,
 'ask': 969,
 'appear': 970,
 'older': 971,
 'cop': 972,
 'business': 973,
 'mess': 974,
 'dream': 975,
 'portrayed': 976,
 'baby': 977,
 'various': 978,
 'front': 979,
 'plenty': 980,
 'creepy': 981,
 'joe': 982,
 'outside': 983,
 'present': 984,
 'spent': 985,
 'reasons': 986,
 'gun': 987,
 'brings': 988,
 'admit': 989,
 'cover': 990,
 'pay': 991,
 'dramatic': 992,
 'telling': 993,
 'bill': 994,
 'deserves': 995,
 'crazy': 996,
 'fairly': 997,
 'break': 998,
 'directors': 999,
 'meant': 1000,
 ...}

In [17]:
print(X_train)

[[1935    1 1200 ...  205  351 3856]
 [   3 1651  595 ...   89  103    9]
 [   0    0    0 ...    2  710   62]
 ...
 [   0    0    0 ... 1641    2  603]
 [   0    0    0 ...  245  103  125]
 [   0    0    0 ...   70   73 2062]]

In [18]:
print(X_test)

[[   0    0    0 ...  995  719  155]
 [  12  162   59 ...  380    7    7]
 [   0    0    0 ...   50 1088   96]
 ...
 [   0    0    0 ...  125  200 3241]
 [   0    0    0 ... 1066    1 2305]
 [   0    0    0 ...    1  332   27]]

## Separate input and output

In [19]:
y_train=train_data['sentiment']
y_test=test_data['sentiment']

In [20]:
print(y_train)

39087    0
30893    0
45278    1
16398    0
13653    0
        ..
11284    1
44732    1
38158    0
860      1
15795    1
Name: sentiment, Length: 40000, dtype: int64

In [21]:
print(y_test)

33553    1
9427     1
199      0
12447    1
39489    0
        ..
28567    0
25079    1
18707    1
15200    0
5857     1
Name: sentiment, Length: 10000, dtype: int64

# Model Building

In [22]:
model = Sequential()
model.add(Input(shape=(200,)))
model.add(Embedding(input_dim=5000, output_dim=128))
model.add(LSTM(128, dropout=0.2, recurrent_dropout=0.2))
model.add(Dense(1, activation='sigmoid'))

In [23]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (None, 200, 128)            │         640,000 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm (LSTM)                          │ (None, 128)                 │         131,584 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 1)                   │             129 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 771,713 (2.94 MB)

 Trainable params: 771,713 (2.94 MB)

 Non-trainable params: 0 (0.00 B)

# Compile Model

In [24]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

# Model Training

In [25]:
model.fit(X_train,y_train, epochs=5,batch_size=64,validation_split=0.2)

Epoch 1/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 356s 701ms/step - accuracy: 0.7844 - loss: 0.4634 - val_accuracy: 0.8487 - val_loss: 0.3594
Epoch 2/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 337s 673ms/step - accuracy: 0.8616 - loss: 0.3385 - val_accuracy: 0.8309 - val_loss: 0.3741
Epoch 3/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 369s 739ms/step - accuracy: 0.8778 - loss: 0.3018 - val_accuracy: 0.8680 - val_loss: 0.3452
Epoch 4/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 359s 719ms/step - accuracy: 0.8669 - loss: 0.3187 - val_accuracy: 0.8729 - val_loss: 0.3206
Epoch 5/5
500/500 ━━━━━━━━━━━━━━━━━━━━ 330s 661ms/step - accuracy: 0.8910 - loss: 0.2720 - val_accuracy: 0.8767 - val_loss: 0.3138

# Model Evaluation

In [26]:
loss,accuracy=model.evaluate(X_test,y_test)
print(loss)
print(accuracy)

313/313 ━━━━━━━━━━━━━━━━━━━━ 21s 64ms/step - accuracy: 0.8781 - loss: 0.3118
0.3118009865283966
0.8780999779701233